### PR TITLE
Added slug to add_superadmin script and sample configs

### LINKED ISSUE #461: Initial setup fails due to missing superadmin slug
Initial setup following the server readme fails with the following error:
```
ERROR:  null value in column "slug" of relation "users" violates not-null constraint
```

### PR DESCRIPTION
**Pull request by BlobbyBob**
Fixes #461 and #421  
Also activates the account by default. I think it is discussable whether this is wanted or not, but for setting up a local dev environment (and probably also a production environment), this makes things more comfortable.

The code from this PR (and further PRs) is licensed under MIT license (in case you want to re-license the whole project at some point).

### CODE REVIEW

**Comment by dorthrithil** [comment]
Thanks for the PR! 
If everything would work correctly, setting the slug manually wouldn't be necessary though. Did you have a look why `update_slugs` in `server/src/models/mixins/has_slug.py` isn't creating the slug automatically? It should be triggered by `db.session.commit()` in the `add_superadmin` script..

**Comment by BlobbyBob** [comment]
Thanks for the hint, these dependencies are not always that easy to grasp in the beginning.

Interestingly, I cannot reproduce this issue today after rolling back all my changes. The only thing I couldn't rollback is my exact environment configuration, so it might depend on that somehow.
I guess I will close my issue and the PR until I can reproduce the issue again.

**Comment by dorthrithil** [comment]
Strange, maybe I'll find smth out in #421

**Comment by BlobbyBob** [comment]
I think I found the issue while working on #473:
Per default, sqlalchemy has `autoflush` enabled, which flushes DB queries to the DBMS whenever needed. However, this might be before `db.session.commit()` and does not trigger the `before_commit` event. Changing the event handler to listen to `before_flush` fixed the issue in my specific case as [`flush` is always executed during `commit`](https://stackoverflow.com/questions/4201455/sqlalchemy-whats-the-difference-between-flush-and-commit#4202016). Maybe it also fixes the issue for other cases

**Comment by dorthrithil** [comment]
Sounds promising! I'll do some tests in #421, but probably that's it. Thanks!

**Pull request closed without merging**
